### PR TITLE
Support for Go Modules

### PR DESCRIPTION
**Pull request by fnxpt**

### CODE REVIEW

**Comment by tandr** [comment]
I think something is amiss there

```
~/ww/r/at/go/hub-client-go (goModules) 
$ go test ./hubclient 
go: downloading gopkg.in/h2non/gock.v1 v1.0.14
go: downloading github.com/stretchr/testify v1.3.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/h2non/parth v0.0.0-20190131123155-b4df798d6542
# github.com/blackducksoftware/hub-client-go/hubclient [github.com/blackducksoftware/hub-client-go/hubclient.test]
hubclient/client_test.go:94:61: undefined: apiCurrentUser
hubclient/client_test.go:107:60: undefined: apiCurrentUser
hubclient/vulnerability-client_test.go:28:26: undefined: apiVulnerabilities
FAIL	github.com/blackducksoftware/hub-client-go/hubclient [build failed]
FAIL
------------------------------------------------------------
```

**Comment by fnxpt** [comment]
Yes I created a ticket for this #79 
I'm afraid this issue was already there

**Comment by tandr** [comment]
yes, looks like that. Are you familiar with code enough to be able to fix it? I don't have an access to Black Duck server anymore, so cannot check what these constants should be expanded to, sorry

**Comment by fnxpt** [comment]
I may be able to have a look, but I think this PR can be merged because its not related with the issue

**Pull request merged**
