### PR TITLE
make http client public so that users can change config settings

### PR DESCRIPTION
**Pull request by mattfenwick**
For example, so that the timeout can be changed.

### CODE REVIEW

**Comment by robpacheco** [comment]
What sort of config changes are you thinking about?

**Comment by jayunit100** [comment]
https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/ Stuff like that , yeah default client needs a lot of tuning

**Comment by robpacheco** [comment]
My concern with expose the client publicly is that its actual methods are not intended to be used directly, but through the methods that exist in the client wrapper. The client wrapper knows how to handle all of the auth and header and tokens and stuff. Is there a way to specify these to the wrapper without having to expose the client directly?

**Comment by jayunit100** [comment]
Fair enough - @matt can we just add 

setTimeout(...)
setTransport(...)

Plumbing so that we don’t expose any other generic functionality of the client ?

**Comment by mattfenwick** [comment]
Okay @jayunit100 @robpacheco updated, can you guys take another look?

**Pull request merged**
